version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Python on CircleCI"
      - python/install-packages
      - run:
          name: Start the application
          command: |
            source venv/bin/activate
            export FLASK_APP=app
            export FLASK_ENV=development
            flask run --host=0.0.0.0 &
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest tests/
    parallelism: 2

workflows:
  build-and-test:
    jobs:
      - build
