version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: virtualenv venv && . venv/bin/activate
      - run: pip install -r requirements.txt
      - run: pytest tests/


