version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - run:
          name: Start Flask app
          command: |
            virtualenv venv && . venv/bin/activate
            pip install -r requirements.txt
            export FLASK_APP=app.py
            flask run --host=127.0.0.1 &
          background: true

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/



