version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install
      - run: pip install -r requirements.txt
      - run: python -m pytest tests/
      - run: |
          if [ "${CIRCLE_BRANCH}" == "main" ]; then
            docker build -t bog-estate .
            docker tag bog-estate chmaikos/bog-estate:latest
            docker push chmaikos/bog-estate:latest
          fi

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
