version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: python3 -m venv venv
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate && \
            pip install -r requirements.txt
      - run:
          name: Start Flask app
          command: |
            . venv/bin/activate && \
            flask run --host=127.0.0.1 > /dev/null 2>&1 &
            sleep 10
      - run:
          name: Run tests
          command: |
            . venv/bin/activate && \
            pytest
workflows:
  build-and-test:
    jobs:
      - build
