version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Python on CircleCI"
      - python/install-packages
      - run:
          name: Run server in background
          command: |
            export DB_USERNAME=$DB_USERNAME
            export DB_PASSWORD=$DB_PASSWORD
            export DB_HOST=$DB_HOST
            flask run
          background: true
      - run:
          name: Run tests
          command: pytest

workflows:
  build-and-test:
    jobs:
      - build
