version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv shell
            pip install -r requirements.txt
      - run:
          name: Start Flask app
          command: |
            pipenv shell
            flask run &
            sleep 30
          background: true
      - run:
          name: Run tests
          command: |
            pipenv shell
            pytest

workflows:
  build-and-test:
    jobs:
      - build
