version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/real-estate-bog
    steps:
      - checkout
      - run: echo "Python on CircleCI"
      - python/install-packages
      - run:
          name: Run server in background
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flask run --host=0.0.0.0
            sleep 30
            cat server.log
          background: true
      - run:
          name: Run pytest
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pytest


workflows:
  build-and-test:
    jobs:
      - build
