version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
            pip install pytest
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pipenv run python -m pytest tests/

