version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Python on CircleCI"
      - python/install-packages
      - run:
          name: Run server in background
          command: |
            python3 -m venv venv
            . venv/bin/activate
            echo 'export DB_USERNAME=$DB_USERNAME' >> $BASH_ENV
            echo 'export DB_PASSWORD=$DB_PASSWORD' >> $BASH_ENV
            echo 'export DB_HOST=$DB_HOST' >> $BASH_ENV
            flask run
            sleep 30
          background: true
      - store_artifacts:
          path: server.log

workflows:
  build-and-test:
    jobs:
      - build
